// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagementApp.Data;

#nullable disable

namespace TaskManagementApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagementApp.Models.TaskItem", b =>
                {
                    b.Property<int>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaskId"));

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Remarks")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("UpdatedBy")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOn")
                        .HasColumnType("datetime2");

                    b.HasKey("TaskId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            TaskId = 1,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 12, 17, 9, 27, 36, 535, DateTimeKind.Utc).AddTicks(6190),
                            Description = "Design the database schema for the Task Management app",
                            DueDate = new DateTime(2025, 12, 24, 9, 27, 36, 535, DateTimeKind.Utc).AddTicks(6186),
                            Remarks = "High priority",
                            Status = 2,
                            Title = "Design Database Schema",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2025, 12, 17, 9, 27, 36, 535, DateTimeKind.Utc).AddTicks(6190)
                        },
                        new
                        {
                            TaskId = 2,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 12, 17, 9, 27, 36, 535, DateTimeKind.Utc).AddTicks(6192),
                            Description = "Create controllers and views for Task CRUD operations",
                            DueDate = new DateTime(2025, 12, 22, 9, 27, 36, 535, DateTimeKind.Utc).AddTicks(6191),
                            Remarks = "Start after DB design",
                            Status = 1,
                            Title = "Implement CRUD Controllers",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2025, 12, 17, 9, 27, 36, 535, DateTimeKind.Utc).AddTicks(6193)
                        },
                        new
                        {
                            TaskId = 3,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 12, 17, 9, 27, 36, 535, DateTimeKind.Utc).AddTicks(6194),
                            Description = "Implement search and status filter in index page",
                            DueDate = new DateTime(2025, 12, 20, 9, 27, 36, 535, DateTimeKind.Utc).AddTicks(6194),
                            Remarks = "Depends on CRUD completion",
                            Status = 4,
                            Title = "Add Search and Filter",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2025, 12, 17, 9, 27, 36, 535, DateTimeKind.Utc).AddTicks(6195)
                        },
                        new
                        {
                            TaskId = 4,
                            CreatedBy = 1,
                            CreatedOn = new DateTime(2025, 12, 17, 9, 27, 36, 535, DateTimeKind.Utc).AddTicks(6197),
                            Description = "Document the project",
                            DueDate = new DateTime(2025, 12, 18, 9, 27, 36, 535, DateTimeKind.Utc).AddTicks(6196),
                            Remarks = "Assignment ready",
                            Status = 3,
                            Title = "Write README.md",
                            UpdatedBy = 1,
                            UpdatedOn = new DateTime(2025, 12, 17, 9, 27, 36, 535, DateTimeKind.Utc).AddTicks(6197)
                        });
                });

            modelBuilder.Entity("TaskManagementApp.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            UserName = "Admin"
                        },
                        new
                        {
                            UserId = 2,
                            UserName = "System"
                        });
                });

            modelBuilder.Entity("TaskManagementApp.Models.TaskItem", b =>
                {
                    b.HasOne("TaskManagementApp.Models.User", "CreatedByUser")
                        .WithMany("CreatedTasks")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskManagementApp.Models.User", "UpdatedByUser")
                        .WithMany("UpdatedTasks")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("TaskManagementApp.Models.User", b =>
                {
                    b.Navigation("CreatedTasks");

                    b.Navigation("UpdatedTasks");
                });
#pragma warning restore 612, 618
        }
    }
}
